services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: ${DB_HOST:-mysql}
      PMA_PORT: ${DB_PORT:-3306}
      PMA_USER: ${DB_USERNAME:-sail}
      PMA_PASSWORD: ${DB_PASSWORD:-password}
    depends_on:
      - mysql
    networks:
      - sail